# Generated by Django 3.1.3 on 2020-11-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_link', models.CharField(max_length=255)),
                ('generated_link', models.CharField(max_length=255)),
            ],
        ),
    ]
